defaults: &defaults
  app_name: "Bootstrap Demo Rails App"
  domain: "http://bootstrap-demo.dev"    
  admin_emails: 
    - "xdite@rocodev.com"
  google_analytics_key: ""
  default_logo_url: "/logo.png"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
